// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByDV1aKTnG9u_9d8oVOQpaDWmx9wcyV4M',
    appId: '1:632561998344:web:84f146eb8ab3b329174fbd',
    messagingSenderId: '632561998344',
    projectId: 'mutamaruna2',
    authDomain: 'mutamaruna2.firebaseapp.com',
    storageBucket: 'mutamaruna2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCflIH76LZc-IlivjAeOn5emZXezyS6VSg',
    appId: '1:632561998344:android:b23d9a0fd2f4b29d174fbd',
    messagingSenderId: '632561998344',
    projectId: 'mutamaruna2',
    storageBucket: 'mutamaruna2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa49ERV9hXNBaF1tfBxl8t62FUY40aGpI',
    appId: '1:632561998344:ios:315a26d7f3e91be5174fbd',
    messagingSenderId: '632561998344',
    projectId: 'mutamaruna2',
    storageBucket: 'mutamaruna2.appspot.com',
    iosBundleId: 'com.example.mutamaruna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa49ERV9hXNBaF1tfBxl8t62FUY40aGpI',
    appId: '1:632561998344:ios:315a26d7f3e91be5174fbd',
    messagingSenderId: '632561998344',
    projectId: 'mutamaruna2',
    storageBucket: 'mutamaruna2.appspot.com',
    iosBundleId: 'com.example.mutamaruna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByDV1aKTnG9u_9d8oVOQpaDWmx9wcyV4M',
    appId: '1:632561998344:web:ba7c8102d4e25870174fbd',
    messagingSenderId: '632561998344',
    projectId: 'mutamaruna2',
    authDomain: 'mutamaruna2.firebaseapp.com',
    storageBucket: 'mutamaruna2.appspot.com',
  );
}
